apiVersion: v1
kind: Pod
metadata:
  name: glue_cawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glue_crawler
  template:
    metadata:
      labels:
        app: glue_crawler
    spec:
      containers:
      - name: glue_cawler
        image:  vijay165/glue_crawler
        ports:
        - containerPort: 80
