apiVersion: apps/v1
kind: Deployment
metadata:
  name: glue-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glue-crawler
  template:
    metadata:
      labels:
        app: glue-crawler
    spec:
      containers:
      - name: glue-crawler
        image:  vijay165/glue_crawler
        ports:
        - containerPort: 80
